### ISSUE TITLE
Confusing documentation for Check chkValidated

### ISSUE THREAD

**Issue by jonathanjouty** [scrive/hpqtypes-extras#20]
https://github.com/scrive/hpqtypes-extras/blob/72e46aa84f14985876d28901b02b5a9e67c91e31/src/Database/PostgreSQL/PQTypes/Model/Check.hs#L18-L19

Huh?
Either the sentence seems inconsistent, or I'm not understanding something...

**Comment by jonathanjouty** [comment]
@arybczak is it supposed to be:
> Set to 'True' if check is created as NOT VALID and **is** validated afterwards.

**Comment by arybczak** [comment]
It was fixed in 29b2e6ff0d171fb5888a94e8c0b6d5ba82c1a29a some time ago.
