### ISSUE TITLE
Quotes in field and relation names

### ISSUE THREAD

**Issue by bugthunk** [scrive/hpqtypes-extras#3]
When there’s a need to use quotes around table names, as for e.g. SQL reserved words as `user`, `hpqtypes-extras` does not take into account that the quotes should be removed in naming indices etc, so this error is produced at run-time:

```
*** Exception: DBException {dbeQueryContext = RawSQL "CREATE UNIQUE INDEX unique_idx__\"user\"__email__d0b61d39671fa2b512ac ON \"user\" (email) WHERE deleted = false" (), dbeError = DetailedQueryError {qeSeverity = "ERROR", qeErrorCode = SyntaxError, qeMessagePrimary = "syntax error at or near \"\"user\"\"", qeMessageDetail = Nothing, qeMessageHint = Nothing, qeStatementPosition = Just 33, qeInternalPosition = Nothing, qeInternalQuery = Nothing, qeContext = Nothing, qeSourceFile = Just "scan.l", qeSourceLine = Just 1081, qeSourceFunction = Just "scanner_yyerror"}}
```
This could apply to naming of foreign and primary keys too, but I'm not sure (I haven't got any yet in my current project and I'm too lazy to try).

I suggest filtering `"` so that one is able to use them in naming stuff (or whatever measure is needed, filtering is just my probably erroneous fix suggestion).

Is this a reasonable request, or is it just messy and one should rather stay away from using SQL-reserved words in relations and fields?

**Comment by arybczak** [comment]
Filtering quotation marks would require some changes compatible with how PostgreSQL treats quoted names (afair casing is preserved if a name is quoted, but I'm not sure about any other quirks).

The workaround I found sensible in the past is to append 's' to a table name if the identifier is a reserved keyword - after all, you're probably storing multiple users in this table anyway ;)

**Comment by bugthunk** [comment]
Yes, my lead dev thought naming relations in plural was idiosyncratic so this is why this issue arose :) I'll probably go with the plural hack anyway...
