### ISSUE TITLE
Add support for renaming columns and tables

### ISSUE THREAD

**Issue by EggBaconAndSpam** [scrive/hpqtypes-extras#33]
Postgres provides
```
ALTER TABLE [ ONLY ] name [ * ]
    RENAME [ COLUMN ] column TO new_column
```
and
```
ALTER TABLE name
    RENAME TO new_name
```

Renames are constant-time (['There is no effect on the stored data.'](https://www.postgresql.org/docs/9.1/sql-altertable.html)).

We should in particular expose a 'rename table' migration, which should carry over the table version from the old table.

**Comment by jsynacek** [comment]
See https://github.com/scrive/hpqtypes-extras/pull/47.
